<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Tests – Machine Learning and Data Science 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../statistics/tutorial_2.html" rel="next">
<link href="../statistics/interference_basics.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-29e2c20b02301cfff04dc8050bf30c7e.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-43df0d6f53b733b42d37fa7808e17715.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-2bcf7be291d79734ada0dea710dd8908.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-6bb28caf545b74723fac9b4cde4209ed.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../statistics/index.html">Statistik</a></li><li class="breadcrumb-item"><a href="../statistics/interference_advanced.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tests</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Machine Learning and Data Science 1</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/jhumci/MECH-B-4-MLDS-MLDS1" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Einleitung</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../dataexploratory/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Umgang mit Daten und Explorative Analyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dataexploratory/data_science.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Science, Statisik, und Machine Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dataexploratory/data_sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Sets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dataexploratory/tutorial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial: Getting Data Tidy and finding Correlation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../statistics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistik</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistics/sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Stichproben und Zufallsvariablen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistics/distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Verteilungen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistics/tutorial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial: Monte Carlo Simulation of Vehicle Component Failure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistics/interference_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Interferenz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistics/interference_advanced.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistics/tutorial_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 2: Understanding Patterns in Grid Loads</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistics/tasks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Übungsaufgaben: Wahrscheinlichkeitsrechnung</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../regression/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regressions-Analyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regressions-Analyse</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#t-test" id="toc-t-test" class="nav-link active" data-scroll-target="#t-test"><span class="header-section-number">6.1</span> T-Test</a>
  <ul class="collapse">
  <li><a href="#one-sample-students-t-test-einstichproben-t-test" id="toc-one-sample-students-t-test-einstichproben-t-test" class="nav-link" data-scroll-target="#one-sample-students-t-test-einstichproben-t-test"><span class="header-section-number">6.1.1</span> One-Sample Student’s T-Test (Einstichproben-t-Test)</a></li>
  <li><a href="#sec-statistics-t-test-barley" id="toc-sec-statistics-t-test-barley" class="nav-link" data-scroll-target="#sec-statistics-t-test-barley"><span class="header-section-number">6.1.2</span> Beispiel: Eiweißgehalt von Braugerste</a></li>
  <li><a href="#sec-statistics-t-test-barley-Two" id="toc-sec-statistics-t-test-barley-Two" class="nav-link" data-scroll-target="#sec-statistics-t-test-barley-Two"><span class="header-section-number">6.1.3</span> Aufgabe: Eiweißgehalt von Braugerste</a></li>
  </ul></li>
  <li><a href="#zwei-stichproben-t-test-independent-samples-t-test" id="toc-zwei-stichproben-t-test-independent-samples-t-test" class="nav-link" data-scroll-target="#zwei-stichproben-t-test-independent-samples-t-test"><span class="header-section-number">6.3</span> Zwei-Stichproben-t-Test (Independent Samples t-Test)</a></li>
  <li><a href="#chi-quadrat-test" id="toc-chi-quadrat-test" class="nav-link" data-scroll-target="#chi-quadrat-test"><span class="header-section-number">6.4</span> Chi-Quadrat-Test</a></li>
  <li><a href="#beispiel-qualität-eines-lieferanten" id="toc-beispiel-qualität-eines-lieferanten" class="nav-link" data-scroll-target="#beispiel-qualität-eines-lieferanten"><span class="header-section-number">6.5</span> Beispiel: Qualität eines Lieferanten</a></li>
  <li><a href="#übersicht-über-statistische-tests" id="toc-übersicht-über-statistische-tests" class="nav-link" data-scroll-target="#übersicht-über-statistische-tests"><span class="header-section-number">6.6</span> Übersicht über Statistische Tests</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/jhumci/MECH-B-4-MLDS-MLDS1/edit/main/statistics/interference_advanced.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/jhumci/MECH-B-4-MLDS-MLDS1/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../statistics/index.html">Statistik</a></li><li class="breadcrumb-item"><a href="../statistics/interference_advanced.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tests</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-statistics-interference_advanced" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tests</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Nach dem zuvor beschriebenen Prinzip der Hypothesentests gibt es verschiedene Tests, die auf unterschiedliche Fragestellungen zugeschnitten sind. In diesem Abschnitt werden einige dieser Tests vorgestellt.</p>
<p>Wir werden uns hier auf einige typische Tests konzentrieren. Es gibt noch viele <a href="https://statsandr.com/blog/files/overview-statistical-tests-statsandr.pdf">weitere Tests</a>, die auf spezielle Fragestellungen zugeschnitten sind. Die hier vorgestellten Tests gehören jedoch zu den wichtigsten und werden in der Praxis häufig verwendet.</p>
<section id="t-test" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="t-test"><span class="header-section-number">6.1</span> T-Test</h2>
<p>Der t-Test ist eine Klasse von statistischen Tests, die verwendet werden, um Hypothesen über den Mittelwert (oder die Differenz von Mittelwerten) einer oder zweier Stichproben zu prüfen, insbesondere wenn die Standardabweichung der Grundgesamtheit unbekannt ist und aus der Stichprobe geschätzt werden muss.</p>
<section id="one-sample-students-t-test-einstichproben-t-test" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="one-sample-students-t-test-einstichproben-t-test"><span class="header-section-number">6.1.1</span> One-Sample Student’s T-Test (Einstichproben-t-Test)</h3>
<p>Beim Einstichproben-t-Test wird <strong>der</strong> Mittelwert einer Stichprobe mit einem vorgegebenen, hypothetischen Wert (<span class="math inline">\(\mu_0\)</span>) verglichen. Der Test wird typischerweise verwendet, wenn die Varianz der Grundgesamtheit unbekannt ist und aus der Stichprobe geschätzt wird. Die t-Verteilung berücksichtigt die zusätzliche Unsicherheit, die durch diese Schätzung entsteht.</p>
<p>Wir legen zunächst den <strong>Typ-I-Fehler</strong> (Signifikanzniveau <span class="math inline">\(\alpha\)</span>) fest. Damit definieren wir die maximale Wahrscheinlichkeit, die wir zu akzeptieren bereit sind, die Nullhypothese (<span class="math inline">\(H_0\)</span>) fälschlicherweise abzulehnen, obwohl sie wahr ist (<span class="math inline">\(P(\text{Ablehnung } H_0 | H_0 \text{ ist wahr}) \leq \alpha\)</span>).</p>
<p>Um zu beurteilen, wie wahrscheinlich die beobachtete Stichprobe unter der Annahme ist, dass die Nullhypothese wahr ist, wird die Teststatistik <span class="math inline">\(t\)</span> berechnet. Diese misst den Unterschied zwischen dem Stichprobenmittelwert <span class="math inline">\(\bar{x}\)</span> und dem hypothetischen Wert <span class="math inline">\(\mu_0\)</span> in Einheiten des Standardfehlers des Mittelwerts. Wörtlich bedeutet die Teststatistik: Um wie viele Standardfehler weicht der Stichprobenmittelwert <span class="math inline">\(\bar{x}\)</span> vom vorgegebenen Wert <span class="math inline">\(\mu_0\)</span> ab?</p>
<p><span class="math display">\[
t = \frac{\bar{x} - \mu_0}{s / \sqrt{n}},
\]</span></p>
<p>wobei <span class="math inline">\(\bar{x}\)</span> der Stichprobenmittelwert, <span class="math inline">\(s\)</span> die Stichprobenstandardabweichung (oft wird die korrigierte Stichprobenstandardabweichung verwendet) und <span class="math inline">\(n\)</span> die Stichprobengröße ist.</p>
<p>Unter der Annahme, dass die Nullhypothese wahr ist und die Daten aus einer normalverteilten Grundgesamtheit stammen, folgt die Teststatistik <span class="math inline">\(t\)</span> einer t-Verteilung mit <span class="math inline">\(n-1\)</span> Freiheitsgraden.</p>
<p>Die Entscheidung über die Ablehnung der Nullhypothese hängt von der Alternativhypothese (<span class="math inline">\(H_1\)</span>) ab:</p>
<ul>
<li>Bei <span class="math inline">\(H_1: \mu &gt; \mu_0\)</span> (rechtseitiger Test) lehnen wir <span class="math inline">\(H_0\)</span> ab, wenn <span class="math inline">\(t &gt; t_{1-\alpha, n-1}\)</span>.</li>
<li>Bei <span class="math inline">\(H_1: \mu &lt; \mu_0\)</span> (linksseitiger Test) lehnen wir <span class="math inline">\(H_0\)</span> ab, wenn <span class="math inline">\(t &lt; t_{\alpha, n-1}\)</span> (was <span class="math inline">\(t &lt; -t_{1-\alpha, n-1}\)</span> entspricht).</li>
<li>Bei <span class="math inline">\(H_1: \mu \neq \mu_0\)</span> (zweiseitiger Test) lehnen wir <span class="math inline">\(H_0\)</span> ab, wenn <span class="math inline">\(|t| &gt; t_{1-\alpha/2, n-1}\)</span>.</li>
</ul>
<p>Der kritische Wert <span class="math inline">\(t_{\text{krit}}\)</span> (z.B. <span class="math inline">\(t_{1-\alpha, n-1}\)</span> oder <span class="math inline">\(t_{1-\alpha/2, n-1}\)</span>) wird aus der <a href="https://de.wikipedia.org/wiki/Studentsche_t-Verteilung">Tabelle der t-Verteilung</a> oder mittels Software bestimmt.</p>
</section>
<section id="sec-statistics-t-test-barley" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="sec-statistics-t-test-barley"><span class="header-section-number">6.1.2</span> Beispiel: Eiweißgehalt von Braugerste</h3>
<p>Eine Brauerei bezieht eine neue Charge Gerste. Für den Brauprozess ist es wichtig, dass der mittlere Eiweißgehalt der Gerste einen bestimmten Grenzwert nicht überschreitet, da ein zu hoher Eiweißgehalt zu unerwünscht starkem Schäumen des Bieres führen kann. Der maximal akzeptable mittlere Eiweißgehalt liegt laut Spezifikation bei <span class="math inline">\(\mu_0 = 11.5\%\)</span>.</p>
<p>Die Brauerei möchte prüfen, ob die neue Charge Gerste diese Spezifikation einhält oder ob der mittlere Eiweißgehalt signifikant höher ist. Dazu wird eine Stichprobe von <span class="math inline">\(n=50\)</span> Körnern aus der Charge entnommen und deren Eiweißgehalt analysiert.</p>
<div id="cell-fig-sec-statistics-hypothesistests-barley" class="cell styled-output" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t <span class="im">as</span> t_dist, norm</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Annahmen für die Simulation (wären in der Realität unbekannt)</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Nehmen wir an, die Charge ist tatsächlich leicht über dem Limit</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>true_mu_barley <span class="op">=</span> <span class="fl">11.8</span>  <span class="co"># Tatsächlicher mittlerer Eiweißgehalt der Charge (%)</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>true_sigma_barley <span class="op">=</span> <span class="fl">0.5</span> <span class="co"># Tatsächliche Standardabweichung des Eiweißgehalts (%)</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Nullhypothese (Grenzwert)</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>mu_0_barley <span class="op">=</span> <span class="fl">11.5</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Stichprobe ziehen</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>n_barley <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Setze einen Seed für Reproduzierbarkeit</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">2024</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>X_barley <span class="op">=</span> np.random.normal(true_mu_barley, true_sigma_barley, n_barley)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Schätzer aus der Stichprobe berechnen</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>x_bar_barley <span class="op">=</span> np.mean(X_barley)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>s_barley <span class="op">=</span> np.std(X_barley, ddof<span class="op">=</span><span class="dv">1</span>) <span class="co"># Korrigierte Stichprobenstandardabweichung</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Stichprobenmittelwert (x̄): </span><span class="sc">{</span>x_bar_barley<span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Stichprobenstandardabweichung (s): </span><span class="sc">{</span>s_barley<span class="sc">:.2f}</span><span class="ss">%"</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Stichprobengröße (n): </span><span class="sc">{</span>n_barley<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot der Stichprobendaten und der Nullhypothese</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>sns.histplot(X_barley, bins<span class="op">=</span><span class="dv">8</span>, kde<span class="op">=</span><span class="va">False</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, label<span class="op">=</span><span class="st">'Stichprobe Eiweißgehalt'</span>, color<span class="op">=</span><span class="st">'darkorange'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>plt.axvline(mu_0_barley, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f'Grenzwert H₀: μ ≤ </span><span class="sc">{</span>mu_0_barley<span class="sc">}</span><span class="ss">%'</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>plt.axvline(x_bar_barley, color<span class="op">=</span><span class="st">'blue'</span>, linestyle<span class="op">=</span><span class="st">'-'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f'Stichprobenmittelwert x̄ = </span><span class="sc">{</span>x_bar_barley<span class="sc">:.2f}</span><span class="ss">%'</span>)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Verteilung des Eiweißgehalts der Gerstenprobe und Grenzwert'</span>)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Eiweißgehalt (%)'</span>)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Häufigkeit'</span>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>plt.grid(axis<span class="op">=</span><span class="st">'y'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stichprobenmittelwert (x̄): 11.80%
Stichprobenstandardabweichung (s): 0.48%
Stichprobengröße (n): 50</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-sec-statistics-hypothesistests-barley" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sec-statistics-hypothesistests-barley-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="interference_advanced_files/figure-html/fig-sec-statistics-hypothesistests-barley-output-2.png" width="808" height="523" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sec-statistics-hypothesistests-barley-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Verteilung des Eiweißgehalts in der Stichprobe und der maximal zulässige Mittelwert (Nullhypothese).
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Durchführung des Hypothesentests:</strong></p>
<ol type="1">
<li><p><strong>Definition der Hypothesen:</strong></p>
<ul>
<li><span class="math inline">\(H_0: \mu \leq 11.5\%\)</span> (Der mittlere Eiweißgehalt der Charge liegt bei oder unter dem Grenzwert). Wir verwenden für die Berechnung den Grenzfall <span class="math inline">\(H_0: \mu = 11.5\%\)</span>.</li>
<li><span class="math inline">\(H_1: \mu &gt; 11.5\%\)</span> (Der mittlere Eiweißgehalt der Charge ist höher als der Grenzwert). Wir wählen einen <strong>einseitigen Test</strong> (rechtsseitig), da uns nur eine Überschreitung des Grenzwerts Sorgen bereitet.</li>
</ul></li>
<li><p><strong>Definition des Signifikanzniveaus:</strong></p>
<ul>
<li>Die Brauerei legt <span class="math inline">\(\alpha = 0.05\)</span> fest.</li>
<li>Das Risiko, eine Charge fälschlicherweise als <em>zu eiweißreich</em> abzulehnen, obwohl sie den Grenzwert einhält (<span class="math inline">\(H_0\)</span> wahr ist), soll maximal 5% betragen.</li>
</ul></li>
<li><p><strong>Berechnung der Teststatistik <span class="math inline">\(t\)</span>:</strong></p>
<ul>
<li><span class="math inline">\(t = \frac{\bar{x} - \mu_0}{s / \sqrt{n}}\)</span></li>
</ul>
<div id="f1afe0e4" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Berechnung der Teststatistik für Gerste</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>standard_error_barley <span class="op">=</span> s_barley <span class="op">/</span> np.sqrt(n_barley)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>t_statistic_barley <span class="op">=</span> (x_bar_barley <span class="op">-</span> mu_0_barley) <span class="op">/</span> standard_error_barley</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Standardfehler (s/√n): </span><span class="sc">{</span>standard_error_barley<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Teststatistik (t): </span><span class="sc">{</span>t_statistic_barley<span class="sc">:.3f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Standardfehler (s/√n): 0.0685
Teststatistik (t): 4.381</code></pre>
</div>
</div>
<ul>
<li>Der berechnete Wert ist <span class="math inline">\(t \approx 4.011\)</span>.</li>
</ul></li>
<li><p><strong>Bestimmung des kritischen Wertes <span class="math inline">\(t_{\text{krit}}\)</span>:</strong></p>
<ul>
<li>Wir führen einen einseitigen Test (rechtsseitig) mit <span class="math inline">\(\alpha = 0.05\)</span> und <span class="math inline">\(n-1 = 50-1 = 49\)</span> Freiheitsgraden durch. Wir suchen den Wert <span class="math inline">\(t_{1-\alpha, n-1} = t_{0.95, 49}\)</span>.</li>
<li>Aus der t-Verteilungstabelle oder mit Software erhalten wir <span class="math inline">\(t_{\text{krit}} \approx 1.677\)</span>.</li>
</ul>
<div id="185e607a" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t <span class="im">as</span> t_dist</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>alpha_barley <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>df_barley <span class="op">=</span> n_barley <span class="op">-</span> <span class="dv">1</span> <span class="co"># Freiheitsgrade</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>t_critical_barley <span class="op">=</span> t_dist.ppf(<span class="dv">1</span> <span class="op">-</span> alpha_barley, df_barley)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Freiheitsgrade (df): </span><span class="sc">{</span>df_barley<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Kritischer Wert (t_krit) für α=</span><span class="sc">{</span>alpha_barley<span class="sc">}</span><span class="ss"> (einseitig): </span><span class="sc">{</span>t_critical_barley<span class="sc">:.3f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Freiheitsgrade (df): 49
Kritischer Wert (t_krit) für α=0.05 (einseitig): 1.677</code></pre>
</div>
</div>
<p>Die Visualisierung der t-Verteilung mit dem Ablehnungsbereich hilft, die Entscheidung zu verstehen:</p>
<div id="cell-fig-sec-statistics-hypothesistests-t-distribution-barley" class="cell styled-output" data-execution_count="4">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>x_t_barley <span class="op">=</span> np.linspace(t_dist.ppf(<span class="fl">0.0001</span>, df_barley), t_dist.ppf(<span class="fl">0.9999</span>, df_barley), <span class="dv">500</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>y_t_barley <span class="op">=</span> t_dist.pdf(x_t_barley, df_barley)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>plt.plot(x_t_barley, y_t_barley, label<span class="op">=</span><span class="ss">f't-Verteilung (df=</span><span class="sc">{</span>df_barley<span class="sc">}</span><span class="ss">)'</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>plt.fill_between(x_t_barley, <span class="dv">0</span>, y_t_barley, where<span class="op">=</span>(x_t_barley <span class="op">&gt;</span> t_critical_barley), color<span class="op">=</span><span class="st">'red'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span><span class="ss">f'Ablehnungsbereich (α=</span><span class="sc">{</span>alpha_barley<span class="sc">}</span><span class="ss">)'</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>plt.axvline(t_statistic_barley, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="ss">f'Teststatistik t = </span><span class="sc">{</span>t_statistic_barley<span class="sc">:.3f}</span><span class="ss">'</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'t-Verteilung, kritischer Wert und Teststatistik (Gersten-Eiweißgehalt)'</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'t-Wert'</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Dichte'</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>plt.grid(alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-sec-statistics-hypothesistests-t-distribution-barley" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sec-statistics-hypothesistests-t-distribution-barley-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="interference_advanced_files/figure-html/fig-sec-statistics-hypothesistests-t-distribution-barley-output-1.png" width="821" height="523" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sec-statistics-hypothesistests-t-distribution-barley-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: t-Verteilung mit 49 Freiheitsgraden und Ablehnungsbereich für den einseitigen Gerstentest (α=0.05).
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Zur Erinnerung: Die t-Verteilung beim Testen</strong></p>
<p>Die t-Verteilung beschreibt, wie sich die Teststatistik <span class="math inline">\(T = \frac{\bar{X} - \mu_0}{S / \sqrt{n}}\)</span> verteilen würde, wenn die Nullhypothese (<span class="math inline">\(H_0: \mu = \mu_0\)</span>) wahr wäre und die Daten aus einer normalverteilten Grundgesamtheit stammen. Wir vergleichen unseren aus der Stichprobe berechneten Wert <span class="math inline">\(t\)</span> mit dieser theoretischen Verteilung, um zu sehen, ob er ein plausibler Wert unter <span class="math inline">\(H_0\)</span> ist oder eher ein extremer, unwahrscheinlicher Wert, der gegen <span class="math inline">\(H_0\)</span> spricht.</p>
</div>
</div></li>
<li><p><strong>Entscheidung:</strong></p>
<ul>
<li><p>Wir vergleichen die Teststatistik <span class="math inline">\(t\)</span> mit dem kritischen Wert <span class="math inline">\(t_{\text{krit}}\)</span>. Regel: Lehne <span class="math inline">\(H_0\)</span> ab, wenn <span class="math inline">\(t &gt; t_{\text{krit}}\)</span>.</p></li>
<li><p>Da <span class="math inline">\(t \approx 4.011 &gt; 1.677 \approx t_{\text{krit}}\)</span>, lehnen wir die Nullhypothese <span class="math inline">\(H_0\)</span> ab.</p></li>
<li><p><strong>Interpretation:</strong> Das Ergebnis ist statistisch signifikant auf dem 5%-Niveau. Es gibt ausreichende Evidenz aus der Stichprobe, um zu schlussfolgern, dass der mittlere Eiweißgehalt dieser Gerstencharge signifikant über dem Grenzwert von 11.5% liegt. Die Brauerei sollte diese Charge möglicherweise nicht verwenden oder entsprechend behandeln, um Probleme mit dem Schaum zu vermeiden.</p></li>
<li><p><strong>p-Wert:</strong> Berechnung der Wahrscheinlichkeit, unter <span class="math inline">\(H_0\)</span> eine Teststatistik zu beobachten, die mindestens so extrem ist wie <span class="math inline">\(t \approx 4.011\)</span>.</p></li>
</ul></li>
</ol>
<p>::: {#36639fd9 .cell execution_count=5} <code>{.python .cell-code}   p_value_barley = 1 - t_dist.cdf(t_statistic_barley, df_barley)   print(f'p-Wert: {p_value_barley:.3e}') # Formatierung in wissenschaftlicher Notation   # Vergleich mit alpha   if p_value_barley &lt; alpha_barley:       print(f"Da p-Wert ({p_value_barley:.3e}) &lt; α ({alpha_barley}), wird H₀ abgelehnt.")   else:       print(f"Da p-Wert ({p_value_barley:.3e}) &gt;= α ({alpha_barley}), wird H₀ nicht abgelehnt.")</code></p>
<p>::: {.cell-output .cell-output-stdout} <code>p-Wert: 3.110e-05   Da p-Wert (3.110e-05) &lt; α (0.05), wird H₀ abgelehnt.</code> ::: :::</p>
<pre><code>* Der p-Wert ist sehr klein ($p \approx 9.98 \times 10^{-5}$). Das bedeutet, es ist extrem unwahrscheinlich, einen Stichprobenmittelwert wie den beobachteten (oder einen noch höheren) zu erhalten, wenn der wahre mittlere Eiweißgehalt der Charge tatsächlich nur 11.5% (oder weniger) wäre. Da $p &lt; \alpha$, wird $H_0$ abgelehnt.</code></pre>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Konsequenz der Testentscheidung</strong></p>
<p>In diesem Beispiel führt die Ablehnung der Nullhypothese zu der Schlussfolgerung, dass der Eiweißgehalt wahrscheinlich zu hoch ist. Dies hat praktische Konsequenzen für die Brauerei (z.B. Ablehnung der Charge, Anpassung des Brauprozesses). Wäre die Nullhypothese nicht abgelehnt worden (<span class="math inline">\(t \leq t_{krit}\)</span> oder <span class="math inline">\(p &gt; \alpha\)</span>), hätte die Brauerei keinen statistischen Grund gehabt, die Charge aufgrund des Eiweißgehalts abzulehnen (basierend auf dieser Stichprobe und dem gewählten Signifikanzniveau).</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Der p-Wert</strong></p>
<p>Der <strong>p-Wert</strong> ist die Wahrscheinlichkeit, unter Annahme der Gültigkeit der Nullhypothese (<span class="math inline">\(H_0\)</span>), ein Ergebnis zu erhalten, das mindestens so extrem ist wie das in der Stichprobe beobachtete Ergebnis (repräsentiert durch die Teststatistik).</p>
<ul>
<li>Ein kleiner p-Wert (typischerweise <span class="math inline">\(p \leq \alpha\)</span>) deutet darauf hin, dass das beobachtete Ergebnis unter <span class="math inline">\(H_0\)</span> sehr unwahrscheinlich ist. Dies liefert Evidenz <em>gegen</em> <span class="math inline">\(H_0\)</span> und führt zur Ablehnung von <span class="math inline">\(H_0\)</span>.</li>
<li>Ein großer p-Wert (<span class="math inline">\(p &gt; \alpha\)</span>) bedeutet, dass das beobachtete Ergebnis unter <span class="math inline">\(H_0\)</span> durchaus plausibel ist. Es gibt keine ausreichende Evidenz, um <span class="math inline">\(H_0\)</span> abzulehnen.</li>
</ul>
<p>Der p-Wert ist <strong>nicht</strong> die Wahrscheinlichkeit, dass <span class="math inline">\(H_0\)</span> wahr ist.</p>
</div>
</div>
</section>
<section id="sec-statistics-t-test-barley-Two" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored"><span class="header-section-number">6.1.3</span> Aufgabe: Eiweißgehalt von Braugerste</h3>
<p>Eine Brauerei prüft, ob der Eiweißgehalt einer neuen Gerstencharge im optimalen Bereich von 10.5% liegt. Ein zu hoher oder zu niedriger Eiweißgehalt kann die Bierqualität beeinträchtigen. Führen Sie einen <strong>zweiseitigen t-Test</strong> durch, um zu testen, ob der mittlere Eiweißgehalt der Charge signifikant von 10.5% abweicht. Verwenden Sie eine Stichprobe von <span class="math inline">\(n=50\)</span> Körnern mit den folgenden Daten:</p>
<ul>
<li>Stichprobenmittelwert: <span class="math inline">\(\bar{x} = 10.47\%\)</span></li>
<li>Stichprobenstandardabweichung: <span class="math inline">\(s = 0.49\%\)</span></li>
<li>Signifikanzniveau: <span class="math inline">\(\alpha = 0.05\)</span></li>
</ul>
<p><strong>Hypothesen:</strong></p>
<ul>
<li><span class="math inline">\(H_0: \mu = 10.5\%\)</span> (Der Eiweißgehalt entspricht dem Zielwert).</li>
<li><span class="math inline">\(H_1: \mu \neq 10.5\%\)</span> (Der Eiweißgehalt weicht ab).</li>
</ul>
<p><strong>Entscheidungsregel:</strong></p>
<ul>
<li>Zweiseitig: <span class="math inline">\(H_0\)</span> wird abgelehnt, wenn <span class="math inline">\(|t| &gt; t_{1-\alpha/2, n-1}\)</span>.</li>
<li>Kritischer Wert <span class="math inline">\(t_{\text{krit}}\)</span> aus einer <a href="https://de.wikipedia.org/wiki/Studentsche_t-Verteilung">t-Verteilungstabelle</a> oder Software.</li>
</ul>
<p>Berechnen Sie die Teststatistik <span class="math inline">\(t\)</span>, den kritischen Wert <span class="math inline">\(t_{\text{krit}}\)</span> und den p-Wert. Entscheiden Sie, ob <span class="math inline">\(H_0\)</span> abgelehnt wird, und interpretieren Sie das Ergebnis.</p>
<div class="callout callout-style-default callout-caution callout-titled" title="Musterlösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Musterlösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<section id="musterlösung" class="level2 callout-body-container callout-body" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="musterlösung"><span class="header-section-number">6.2</span> Musterlösung</h2>
<p><strong>Schritt 1: Gegebene Werte</strong> - <span class="math inline">\(\bar{x} = 10.47\%\)</span>, <span class="math inline">\(s = 0.49\%\)</span>, <span class="math inline">\(n = 50\)</span>, <span class="math inline">\(\mu_0 = 10.5\%\)</span>, <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p><strong>Schritt 2: Teststatistik berechnen</strong> Die Formel für die Teststatistik ist:</p>
<p><span class="math display">\[
t = \frac{\bar{x} - \mu_0}{s / \sqrt{n}}
\]</span></p>
<p>Standardfehler: <span class="math inline">\(s / \sqrt{n} = 0.49 / \sqrt{50} \approx 0.0693\)</span></p>
<p>Teststatistik:</p>
<p><span class="math display">\[
t = \frac{10.47 - 10.5}{0.0693} \approx -0.433
\]</span></p>
<div id="fd3b209d" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>x_bar <span class="op">=</span> <span class="fl">10.47</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> <span class="fl">0.49</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>mu_0 <span class="op">=</span> <span class="fl">10.5</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>standard_error <span class="op">=</span> s <span class="op">/</span> np.sqrt(n)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>t_statistic <span class="op">=</span> (x_bar <span class="op">-</span> mu_0) <span class="op">/</span> standard_error</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Standardfehler: </span><span class="sc">{</span>standard_error<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Teststatistik t: </span><span class="sc">{</span>t_statistic<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Standardfehler: 0.0693
Teststatistik t: -0.433</code></pre>
</div>
</div>
<p><strong>Schritt 3: Kritischer Wert</strong></p>
<p>Freiheitsgrade: <span class="math inline">\(df = n - 1 = 49\)</span>. Für einen zweiseitigen Test mit <span class="math inline">\(\alpha = 0.05\)</span> ist der kritische Wert <span class="math inline">\(t_{1-\alpha/2, 49} = t_{0.975, 49} \approx 2.010\)</span> (aus t-Tabelle oder Software).</p>
<div id="b942d393" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t <span class="im">as</span> t_dist</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> n <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>t_critical <span class="op">=</span> t_dist.ppf(<span class="dv">1</span> <span class="op">-</span> alpha<span class="op">/</span><span class="dv">2</span>, df)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Kritischer Wert t_krit: ±</span><span class="sc">{</span>t_critical<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Kritischer Wert t_krit: ±2.010</code></pre>
</div>
</div>
<p><strong>Schritt 4: p-Wert</strong></p>
<p>Der p-Wert für einen zweiseitigen Test ist: <span class="math inline">\(p = 2 \cdot P(T \geq |t|)\)</span>.</p>
<div id="58b212ca" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> t_dist.cdf(<span class="bu">abs</span>(t_statistic), df))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-Wert: </span><span class="sc">{</span>p_value<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>p-Wert: 0.667</code></pre>
</div>
</div>
<p>Ergebnis: <span class="math inline">\(p \approx 0.667\)</span>.</p>
<p><strong>Schritt 5: Entscheidung</strong></p>
<ul>
<li>Vergleich: <span class="math inline">\(|t| \approx 0.433 &lt; 2.010 \approx t_{\text{krit}}\)</span>, daher wird <span class="math inline">\(H_0\)</span> nicht abgelehnt.</li>
<li>Alternativ: <span class="math inline">\(p \approx 0.667 &gt; 0.05\)</span>, bestätigt die Nicht-Ablehnung.</li>
</ul>
<p><strong>Interpretation</strong></p>
<p>Es gibt keinen statistischen Hinweis, dass der Eiweißgehalt der Gerstencharge signifikant von 10.5% abweicht. Die Charge liegt im optimalen Bereich, und die Brauerei kann sie verwenden, ohne Anpassungen vornehmen zu müssen.</p>
</section>
</div>
</div>
</section>
</section>
<section id="zwei-stichproben-t-test-independent-samples-t-test" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="zwei-stichproben-t-test-independent-samples-t-test"><span class="header-section-number">6.3</span> Zwei-Stichproben-t-Test (Independent Samples t-Test)</h2>
<p>Häufig ist man daran interessiert, ob sich die Mittelwerte zweier <strong>unabhängiger</strong> Stichproben signifikant voneinander unterscheiden. Zum Beispiel könnten wir vergleichen, ob sich die mittlere Zugfestigkeit von Stählen zweier verschiedener Lieferanten unterscheidet. Auch hierfür kann ein t-Test eingesetzt werden (vgl. Abb. <a href="#fig-sec-statistics-hypothesistests-two-sample-t-test" class="quarto-xref">Figure&nbsp;<span>6.3</span></a>).</p>
<div id="fig-sec-statistics-hypothesistests-two-sample-t-test" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sec-statistics-hypothesistests-two-sample-t-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="https://upload.wikimedia.org/wikipedia/commons/3/35/Two_sample_ttest.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sec-statistics-hypothesistests-two-sample-t-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Grundidee des Zwei-Stichproben-t-Tests: Vergleich der Mittelwerte zweier Verteilungen. Quelle: <span class="citation" data-cites="Inductiveload_TwoSampleTTest">Inductiveload (<a href="../references.html#ref-Inductiveload_TwoSampleTTest" role="doc-biblioref">n.d.</a>)</span>
</figcaption>
</figure>
</div>
<p><strong>Voraussetzungen:</strong></p>
<ol type="1">
<li>Die beiden Stichproben sind <strong>unabhängig</strong> voneinander.</li>
<li>Die Daten in beiden Stichproben stammen aus <strong>normalverteilten</strong> Grundgesamtheiten. (Der Test ist robust gegenüber Verletzungen dieser Annahme bei ausreichender Stichprobengröße, ca. n &gt; 30 pro Gruppe).</li>
<li>Die <strong>Varianzen</strong> der beiden Grundgesamtheiten sind <strong>gleich</strong> (<span class="math inline">\(\sigma_1^2 = \sigma_2^2\)</span>). Diese Annahme kann mit Tests wie dem Levene-Test überprüft werden. Wenn die Varianzen ungleich sind, wird eine Variante des t-Tests namens Welch-Test verwendet, der die Freiheitsgrade anpasst.</li>
</ol>
<p><strong>Hypothesen (Standardfall: Test auf Gleichheit der Mittelwerte):</strong></p>
<ul>
<li><span class="math inline">\(H_0: \mu_1 = \mu_2\)</span> (oder äquivalent <span class="math inline">\(H_0: \mu_1 - \mu_2 = 0\)</span>)</li>
<li><span class="math inline">\(H_1: \mu_1 \neq \mu_2\)</span> (zweiseitig), oder <span class="math inline">\(H_1: \mu_1 &gt; \mu_2\)</span> (rechtsseitig), oder <span class="math inline">\(H_1: \mu_1 &lt; \mu_2\)</span> (linksseitig)</li>
</ul>
<p><strong>Teststatistik (bei gleichen Varianzen):</strong></p>
<ol type="1">
<li><p>Berechne die <strong>gepoolte (kombinierte) Varianz</strong> <span class="math inline">\(s_p^2\)</span> als gewichteten Durchschnitt der beiden Stichprobenvarianzen: <span class="math display">\[
s_p^2 = \frac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2}
\]</span> wobei <span class="math inline">\(n_1, n_2\)</span> die Stichprobengrößen und <span class="math inline">\(s_1^2, s_2^2\)</span> die (korrigierten) Stichprobenvarianzen sind. <span class="math inline">\(s_p = \sqrt{s_p^2}\)</span> ist die gepoolte Standardabweichung.</p></li>
<li><p>Berechne die <strong>Teststatistik <span class="math inline">\(t\)</span></strong>: <span class="math display">\[
t = \frac{(\bar{x}_1 - \bar{x}_2) - (\mu_1 - \mu_2)_0}{s_p \sqrt{\frac{1}{n_1} + \frac{1}{n_2}}}
\]</span> Für den Standardtest auf Gleichheit ist <span class="math inline">\((\mu_1 - \mu_2)_0 = 0\)</span>, also vereinfacht sich die Formel zu: <span class="math display">\[
t = \frac{\bar{x}_1 - \bar{x}_2}{s_p \sqrt{\frac{1}{n_1} + \frac{1}{n_2}}}
\]</span></p></li>
</ol>
<p><strong>Freiheitsgrade und Entscheidung:</strong></p>
<ul>
<li>Die Teststatistik folgt unter <span class="math inline">\(H_0\)</span> einer t-Verteilung mit <span class="math inline">\(df = n_1 + n_2 - 2\)</span> Freiheitsgraden.</li>
<li>Bestimme den kritischen Wert <span class="math inline">\(t_{\text{krit}}\)</span> basierend auf <span class="math inline">\(\alpha\)</span>, den Freiheitsgraden <span class="math inline">\(df\)</span> und der Alternativhypothese (ein- oder zweiseitig, z.B. <span class="math inline">\(t_{1-\alpha/2, df}\)</span> für zweiseitig).</li>
<li>Vergleiche <span class="math inline">\(t\)</span> mit <span class="math inline">\(t_{\text{krit}}\)</span>. Bei einem zweiseitigen Test: Lehne <span class="math inline">\(H_0\)</span> ab, wenn <span class="math inline">\(|t| &gt; t_{\text{krit}}\)</span>.</li>
<li>Alternativ: Berechne den p-Wert und vergleiche ihn mit <span class="math inline">\(\alpha\)</span>. Lehne <span class="math inline">\(H_0\)</span> ab, wenn <span class="math inline">\(p \leq \alpha\)</span>.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Test auf eine spezifische Differenz der Erwartungswerte</strong></p>
<p>Statt auf Gleichheit der Mittelwerte (<span class="math inline">\(\mu_1 - \mu_2 = 0\)</span>) zu testen, könnte man auch prüfen, ob sich die Mittelwerte um einen bestimmten Betrag <span class="math inline">\(\omega_0\)</span> unterscheiden. Die Nullhypothese wäre dann <span class="math inline">\(H_0: \mu_1 - \mu_2 = \omega_0\)</span>. Die Teststatistik <span class="math inline">\(t\)</span> wird dann wie folgt berechnet: <span class="math display">\[
t = \frac{(\bar{x}_1 - \bar{x}_2) - \omega_0}{s_p \sqrt{\frac{1}{n_1} + \frac{1}{n_2}}}
\]</span> Die Freiheitsgrade der t-Verteilung bleiben <span class="math inline">\(n_1 + n_2 - 2\)</span> (bei Varianzgleichheit).</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Test bei gepaarten Stichproben (Paired Samples t-Test)</strong></p>
<p>In manchen Fällen sind die beiden Stichproben <strong>nicht unabhängig</strong>, sondern <strong>gepaart</strong>. Das klassische Beispiel ist eine Messung <em>vor</em> und <em>nach</em> einer Behandlung an denselben Untersuchungseinheiten (z.B. Patienten, Bauteilen). Hier interessiert uns nicht der Unterschied der Mittelwerte unabhängiger Gruppen, sondern der mittlere Unterschied <em>innerhalb</em> der Paare.</p>
<p>Beispiel: Ein Verfahren zum Härten eines metallischen Bauteils soll untersucht werden. Im Experiment wird der Härtegrad von <span class="math inline">\(n=10\)</span> Bauteilen jeweils <em>vor</em> und <em>nach</em> der Behandlung gemessen.</p>
<p>Tabelle: Härtegrad in HR (Rockwell) vor und nach der Behandlung</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Bauteil</th>
<th style="text-align: left;">1</th>
<th style="text-align: left;">2</th>
<th style="text-align: left;">3</th>
<th style="text-align: left;">4</th>
<th style="text-align: left;">5</th>
<th style="text-align: left;">6</th>
<th style="text-align: left;">7</th>
<th style="text-align: left;">8</th>
<th style="text-align: left;">9</th>
<th style="text-align: left;">10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Vorher</td>
<td style="text-align: left;">49.1</td>
<td style="text-align: left;">49.2</td>
<td style="text-align: left;">49.3</td>
<td style="text-align: left;">49.4</td>
<td style="text-align: left;">49.5</td>
<td style="text-align: left;">49.6</td>
<td style="text-align: left;">49.7</td>
<td style="text-align: left;">49.8</td>
<td style="text-align: left;">49.0</td>
<td style="text-align: left;">50.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nachher</td>
<td style="text-align: left;">50.2</td>
<td style="text-align: left;">50.3</td>
<td style="text-align: left;">50.3</td>
<td style="text-align: left;">50.2</td>
<td style="text-align: left;">50.7</td>
<td style="text-align: left;">50.7</td>
<td style="text-align: left;">50.8</td>
<td style="text-align: left;">50.9</td>
<td style="text-align: left;">51.0</td>
<td style="text-align: left;">51.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Differenz (Nachher - Vorher)</td>
<td style="text-align: left;">1.1</td>
<td style="text-align: left;">1.1</td>
<td style="text-align: left;">1.0</td>
<td style="text-align: left;">0.8</td>
<td style="text-align: left;">1.2</td>
<td style="text-align: left;">1.1</td>
<td style="text-align: left;">1.1</td>
<td style="text-align: left;">1.1</td>
<td style="text-align: left;">2.0</td>
<td style="text-align: left;">1.1</td>
</tr>
</tbody>
</table>
<p><strong>Vorgehen:</strong></p>
<ol type="1">
<li>Berechne die <strong>Differenzen</strong> <span class="math inline">\(d_i = \text{Wert}_{\text{nachher}, i} - \text{Wert}_{\text{vorher}, i}\)</span> für jedes Paar <span class="math inline">\(i\)</span>.</li>
<li>Behandle diese Differenzen <span class="math inline">\(d_1, d_2, ..., d_n\)</span> als <strong>eine einzelne Stichprobe</strong>.</li>
<li>Führe einen <strong>Einstichproben-t-Test</strong> für diese Differenzen durch, um zu prüfen, ob der mittlere Unterschied <span class="math inline">\(\mu_d\)</span> signifikant von einem bestimmten Wert (meistens 0) abweicht.</li>
</ol>
<p><strong>Hypothesen (Test auf signifikante Erhöhung):</strong></p>
<ul>
<li><span class="math inline">\(H_0: \mu_d = 0\)</span> (Die Behandlung hat im Mittel keinen Effekt auf die Härte.)</li>
<li><span class="math inline">\(H_1: \mu_d &gt; 0\)</span> (Die Behandlung erhöht im Mittel den Härtegrad.)</li>
</ul>
<p><strong>Berechnungen:</strong></p>
<ul>
<li>Berechne den Mittelwert der Differenzen <span class="math inline">\(\bar{d}\)</span> und die Standardabweichung der Differenzen <span class="math inline">\(s_d\)</span>.</li>
</ul>
<div id="425bd2d7" class="cell styled-output" data-execution_count="9">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t <span class="im">as</span> t_dist</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>vorher <span class="op">=</span> np.array([<span class="fl">49.1</span>, <span class="fl">49.2</span>, <span class="fl">49.3</span>, <span class="fl">49.4</span>, <span class="fl">49.5</span>, <span class="fl">49.6</span>, <span class="fl">49.7</span>, <span class="fl">49.8</span>, <span class="fl">49.0</span>, <span class="fl">50.0</span>])</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>nachher <span class="op">=</span> np.array([<span class="fl">50.2</span>, <span class="fl">50.3</span>, <span class="fl">50.3</span>, <span class="fl">50.2</span>, <span class="fl">50.7</span>, <span class="fl">50.7</span>, <span class="fl">50.8</span>, <span class="fl">50.9</span>, <span class="fl">51.0</span>, <span class="fl">51.1</span>])</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> nachher <span class="op">-</span> vorher</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Differenzen (d):"</span>, d)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>d_bar <span class="op">=</span> np.mean(d)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>s_d <span class="op">=</span> np.std(d, ddof<span class="op">=</span><span class="dv">1</span>) <span class="co"># Korrigierte Standardabweichung</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(d)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Mittlere Differenz (d̄): </span><span class="sc">{</span>d_bar<span class="sc">:.3f}</span><span class="ss">'</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Standardabweichung der Differenzen (s_d): </span><span class="sc">{</span>s_d<span class="sc">:.3f}</span><span class="ss">'</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Anzahl Paare (n): </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Teststatistik berechnen (H0: mu_d = 0)</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>mu_d0 <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>t_stat_paired <span class="op">=</span> (d_bar <span class="op">-</span> mu_d0) <span class="op">/</span> (s_d <span class="op">/</span> np.sqrt(n))</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Teststatistik (t): </span><span class="sc">{</span>t_stat_paired<span class="sc">:.3f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Differenzen (d): [1.1 1.1 1.  0.8 1.2 1.1 1.1 1.1 2.  1.1]
Mittlere Differenz (d̄): 1.160
Standardabweichung der Differenzen (s_d): 0.313
Anzahl Paare (n): 10
Teststatistik (t): 11.705</code></pre>
</div>
</div>
<ul>
<li>Der mittlere Unterschied beträgt <span class="math inline">\(\bar{d} \approx 1.16\)</span> und die Standardabweichung <span class="math inline">\(s_d \approx 0.317\)</span>. Die Teststatistik ist <span class="math inline">\(t \approx 11.58\)</span>.</li>
</ul>
<p><strong>Testdurchführung:</strong></p>
<ol type="1">
<li><p><strong>Voraussetzungen:</strong> Die <em>Differenzen</em> sollten annähernd normalverteilt sein (oder <span class="math inline">\(n\)</span> groß genug). Die Messungen sind gepaart.</p></li>
<li><p><strong>Hypothesen:</strong> <span class="math inline">\(H_0: \mu_d = 0\)</span>, <span class="math inline">\(H_1: \mu_d &gt; 0\)</span>.</p></li>
<li><p><strong>Signifikanzniveau:</strong> <span class="math inline">\(\alpha = 0.05\)</span>.</p></li>
<li><p><strong>Teststatistik:</strong> <span class="math inline">\(t = \frac{\bar{d} - 0}{s_d / \sqrt{n}} \approx 11.58\)</span>.</p></li>
<li><p><strong>Kritischer Wert:</strong> Für einen einseitigen Test mit <span class="math inline">\(\alpha = 0.05\)</span> und <span class="math inline">\(df = n-1 = 10-1 = 9\)</span> Freiheitsgraden ist <span class="math inline">\(t_{\text{krit}} = t_{0.95, 9}\)</span>.</p>
<div id="7faec674" class="cell styled-output" data-execution_count="10">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>df_paired <span class="op">=</span> n <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>alpha_paired <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>t_crit_paired <span class="op">=</span> t_dist.ppf(<span class="dv">1</span> <span class="op">-</span> alpha_paired, df_paired)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Freiheitsgrade (df): </span><span class="sc">{</span>df_paired<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Kritischer Wert (t_krit) für α=</span><span class="sc">{</span>alpha_paired<span class="sc">}</span><span class="ss"> (einseitig): </span><span class="sc">{</span>t_crit_paired<span class="sc">:.3f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Freiheitsgrade (df): 9
Kritischer Wert (t_krit) für α=0.05 (einseitig): 1.833</code></pre>
</div>
</div>
<p>Der kritische Wert ist <span class="math inline">\(t_{\text{krit}} \approx 1.833\)</span>.</p></li>
<li><p><strong>Entscheidung:</strong> Da <span class="math inline">\(t \approx 11.58 &gt; 1.833 \approx t_{\text{krit}}\)</span>, lehnen wir <span class="math inline">\(H_0\)</span> ab.</p>
<ul>
<li><strong>Interpretation:</strong> Es gibt starke statistische Evidenz dafür, dass die Behandlung den Härtegrad der Bauteile signifikant erhöht.</li>
<li><strong>p-Wert:</strong></li>
</ul></li>
</ol>
<div id="6da020bd" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>p_value_paired <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> t_dist.cdf(t_stat_paired, df_paired)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'p-Wert (einseitig): </span><span class="sc">{</span>p_value_paired<span class="sc">:.3e}</span><span class="ss">'</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> p_value_paired <span class="op">&lt;</span> alpha_paired:</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Da p-Wert (</span><span class="sc">{</span>p_value_paired<span class="sc">:.3e}</span><span class="ss">) &lt; α (</span><span class="sc">{</span>alpha_paired<span class="sc">}</span><span class="ss">), wird H₀ abgelehnt."</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">print</span>(<span class="ss">f"Da p-Wert (</span><span class="sc">{</span>p_value_paired<span class="sc">:.3e}</span><span class="ss">) &gt;= α (</span><span class="sc">{</span>alpha_paired<span class="sc">}</span><span class="ss">), wird H₀ nicht abgelehnt."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>p-Wert (einseitig): 4.760e-07
Da p-Wert (4.760e-07) &lt; α (0.05), wird H₀ abgelehnt.</code></pre>
</div>
</div>
<pre><code>Der p-Wert ist extrem klein ($p \approx 1.35 \times 10^{-6}$), was die Ablehnung von $H_0$ bestätigt.</code></pre>
</div>
</div>
</section>
<section id="chi-quadrat-test" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="chi-quadrat-test"><span class="header-section-number">6.4</span> Chi-Quadrat-Test</h2>
<p>Der Chi-Quadrat-Test prüft Hypothesen über kategoriale Daten, z. B. ob beobachtete Häufigkeiten mit erwarteten Häufigkeiten übereinstimmen. Ein häufiger Anwendungsfall ist der <strong>Anpassungstest</strong> (Goodness-of-Fit), der testet, ob eine Stichprobe einer bestimmten Verteilung entspricht.</p>
<p>Die Teststatistik misst die Abweichung zwischen beobachteten (<span class="math inline">\(O_i\)</span>) und erwarteten (<span class="math inline">\(E_i\)</span>) Häufigkeiten:</p>
<p><span class="math display">\[
\chi^2 = \sum \frac{(O_i - E_i)^2}{E_i}
\]</span></p>
<p>Unter der Nullhypothese (<span class="math inline">\(H_0\)</span>) folgt die Statistik einer Chi-Quadrat-Verteilung mit <span class="math inline">\(k-1\)</span> Freiheitsgraden (<span class="math inline">\(k\)</span> = Anzahl Kategorien). Ein großer <span class="math inline">\(\chi^2\)</span>-Wert spricht gegen <span class="math inline">\(H_0\)</span>.</p>
</section>
<section id="beispiel-qualität-eines-lieferanten" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="beispiel-qualität-eines-lieferanten"><span class="header-section-number">6.5</span> Beispiel: Qualität eines Lieferanten</h2>
<p>Ein neuer Lieferant (A) liefert Bauteile, die in vier Kategorien eingeteilt werden: „OK“, „Fehler 1“, „Fehler 2“, „Fehler 3“. Wir prüfen, ob die Qualitätsverteilung von Lieferant A mit der bisherigen Verteilung (erwartete Anteile: OK: 81%, Fehler 1: 8%, Fehler 2: 6%, Fehler 3: 5%) übereinstimmt. Stichprobe: <span class="math inline">\(n=120\)</span> Teile.</p>
<p><strong>Beobachtete Häufigkeiten:</strong></p>
<ul>
<li>OK: 100</li>
<li>Fehler 1: 10</li>
<li>Fehler 2: 5</li>
<li>Fehler 3: 5</li>
</ul>
<p><strong>Erwartete Häufigkeiten:</strong></p>
<ul>
<li>OK: <span class="math inline">\(120 \times 0.81 = 97.2\)</span></li>
<li>Fehler 1: <span class="math inline">\(120 \times 0.08 = 9.6\)</span></li>
<li>Fehler 2: <span class="math inline">\(120 \times 0.06 = 7.2\)</span></li>
<li>Fehler 3: <span class="math inline">\(120 \times 0.05 = 6.0\)</span></li>
</ul>
<p><strong>Hypothesen:</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Lieferant A hat die gleiche Qualitätsverteilung wie bisherige Lieferanten.</li>
<li><span class="math inline">\(H_1\)</span>: Die Verteilung unterscheidet sich.</li>
</ul>
<p><strong>Testdurchführung:</strong></p>
<ol type="1">
<li><strong>Voraussetzungen:</strong> Erwartete Häufigkeiten <span class="math inline">\(E_i \geq 5\)</span>, Stichprobe zufällig.</li>
<li><strong>Signifikanzniveau:</strong> <span class="math inline">\(\alpha = 0.05\)</span>.</li>
<li><strong>Teststatistik:</strong></li>
</ol>
<div id="8db4c7ed" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> chi2</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>O <span class="op">=</span> np.array([<span class="dv">100</span>, <span class="dv">10</span>, <span class="dv">5</span>, <span class="dv">5</span>])</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>E <span class="op">=</span> np.array([<span class="fl">97.2</span>, <span class="fl">9.6</span>, <span class="fl">7.2</span>, <span class="fl">6.0</span>])</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>chi2_statistic <span class="op">=</span> np.<span class="bu">sum</span>((O <span class="op">-</span> E)<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> E)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Chi-Quadrat Statistik: </span><span class="sc">{</span>chi2_statistic<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Chi-Quadrat Statistik: 0.936</code></pre>
</div>
</div>
<p>Ergebnis: <span class="math inline">\(\chi^2 \approx 0.936\)</span>.</p>
<ol start="4" type="1">
<li><strong>Kritischer Wert:</strong></li>
</ol>
<p>Für <span class="math inline">\(df = 4-1 = 3\)</span> und <span class="math inline">\(\alpha = 0.05\)</span> ist <span class="math inline">\(\chi^2_{\text{krit}} \approx 7.815\)</span>.</p>
<ol start="5" type="1">
<li><strong>Entscheidung:</strong></li>
</ol>
<p>Da <span class="math inline">\(\chi^2 \approx 0.936 &lt; 7.815\)</span>, wird <span class="math inline">\(H_0\)</span> nicht abgelehnt.</p>
<p><strong>Interpretation:</strong></p>
<p>Es gibt keinen Hinweis, dass sich die Qualität von Lieferant A signifikant von bisherigen Lieferanten unterscheidet.</p>
<div id="a4a3d65e" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> chi2.cdf(chi2_statistic, <span class="dv">3</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-Wert: </span><span class="sc">{</span>p_value<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>p-Wert: 0.817</code></pre>
</div>
</div>
<p><strong>p-Wert:</strong> <span class="math inline">\(p \approx 0.817 &gt; 0.05\)</span>, bestätigt die Nicht-Ablehnung von <span class="math inline">\(H_0\)</span>.</p>
</section>
<section id="übersicht-über-statistische-tests" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="übersicht-über-statistische-tests"><span class="header-section-number">6.6</span> Übersicht über Statistische Tests</h2>
<p>Grundsätzlich setzen wir statischtische Tests ein, wenn wir eine Hypothese über eine Grundgesamtheit aufstellen und diese Hypothese auf Basis einer Stichprobe überprüfen wollen. Die Hypothese wird in eine Nullhypothese <span class="math inline">\(H_0\)</span> und eine Alternativhypothese <span class="math inline">\(H_1\)</span> aufgeteilt. Die Nullhypothese ist die Hypothese, die wir widerlegen wollen, während die Alternativhypothese die Hypothese ist, die wir annehmen, wenn die Nullhypothese widerlegt wird.</p>
<p>Test ermöglichen und zu unterschieden, ob die durch uns auf Grund der Stichprobe getroffene Aussage auf die Grundgesamtheit übertragbar oder möglicherweise nur Zufall sind.</p>
<!-- Hier Einen Link zu möglichen Fragestellungen und tests einführen -->


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Inductiveload_TwoSampleTTest" class="csl-entry" role="listitem">
Inductiveload, based on original work by Jhguch. n.d. <span>“Two Sample t-Test.”</span> <a href="https://commons.wikimedia.org/wiki/File:Two_sample_ttest.svg">https://commons.wikimedia.org/wiki/File:Two_sample_ttest.svg</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/jhumci\.github\.io\/MECH-B-4-MLDS-MLDS1");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../statistics/interference_basics.html" class="pagination-link" aria-label="Interferenz">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Interferenz</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../statistics/tutorial_2.html" class="pagination-link" aria-label="Tutorial 2: Understanding Patterns in Grid Loads">
        <span class="nav-page-text">Tutorial 2: Understanding Patterns in Grid Loads</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Machine Learning and Data Science 1 SoSe 2025 (MECH-B-4-MLDS-MLDS1)</p>
</div>   
    <div class="nav-footer-center">
<p><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> Julian Huber</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/jhumci/MECH-B-4-MLDS-MLDS1/edit/main/statistics/interference_advanced.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/jhumci/MECH-B-4-MLDS-MLDS1/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>